const allObjects = {
    "agate": {
        id: "agate",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "aklys": {
        id: "aklys",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "alchemy smock": {
        id: "alchemy smock",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "almond-wood walking stick": {
        id: "almond-wood walking stick",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "amber": {
        id: "amber",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "amethyst": {
        id: "amethyst",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "amulet of change": {
        id: "amulet of change",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of esp": {
        id: "amulet of esp",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of flying": {
        id: "amulet of flying",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of guarding": {
        id: "amulet of guarding",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of life saving": {
        id: "amulet of life saving",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of magical breathing": {
        id: "amulet of magical breathing",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of reflection": {
        id: "amulet of reflection",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of restful sleep": {
        id: "amulet of restful sleep",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of strangulation": {
        id: "amulet of strangulation",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of unchanging": {
        id: "amulet of unchanging",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of yendor": {
        id: "amulet of yendor",
        symbol: "?",
        class1: "hi_metal",
        class2: "",
        is_artifact: false,
        color: "HI_METAL",
    },
    "amulet versus poison": {
        id: "amulet versus poison",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "ancient defense": {
        id: "ancient defense",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BRIGHT_CYAN",
    },
    "anointing oil of enlightenment": {
        id: "enlightenment",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "anointing oil of extra healing": {
        id: "extra healing",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_RED",
    },
    "anointing oil of full healing": {
        id: "full healing",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "anointing oil of gain energy": {
        id: "gain energy",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "anointing oil of gain level": {
        id: "gain level",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "anointing oil of healing": {
        id: "healing",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "anointing oil of invisibility": {
        id: "invisibility",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_BRIGHT_BLUE",
    },
    "anointing oil of monster detection": {
        id: "monster detection",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "anointing oil of object detection": {
        id: "object detection",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "anointing oil of restore ability": {
        id: "restore ability",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_BRIGHT_MAGENTA",
    },
    "anointing oil of see invisible": {
        id: "see invisible",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "anointing oil of speed": {
        id: "speed",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "anointing oil of wiggy gain ability": {
        id: "wiggy gain ability",
        symbol: "φ",
        class1: "anointing oils",
        class2: "bottle of anointing oil",
        is_artifact: false,
        color: "CLR_RED",
    },
    "apostolic writing kit": {
        id: "apostolic writing kit",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "CLR_WHITE",
    },
    "apple": {
        id: "apple",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_RED",
    },
    "aquamarine": {
        id: "aquamarine",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "arrow": {
        id: "arrow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "athame": {
        id: "athame",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "axe": {
        id: "axe",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "bag of holding": {
        id: "bag of holding",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "bag of tricks": {
        id: "bag of tricks",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "banana": {
        id: "banana",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "banded mail": {
        id: "banded mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "bardiche": {
        id: "bardiche",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "battle-axe": {
        id: "battle-axe",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "beartrap": {
        id: "beartrap",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "bec de corbin": {
        id: "bec de corbin",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "bell": {
        id: "bell",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "bell of opening": {
        id: "bell of opening",
        symbol: "?",
        class1: "hi_silver",
        class2: "",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "belt of truth": {
        id: "belt of truth",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "bill-guisarme": {
        id: "bill-guisarme",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "black dragon scale mail": {
        id: "black dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "black dragon scales": {
        id: "black dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "black opal": {
        id: "black opal",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "blindfold": {
        id: "blindfold",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "blue dragon scale mail": {
        id: "blue dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "blue dragon scales": {
        id: "blue dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "book of the dead": {
        id: "book of the dead",
        symbol: "?",
        class1: "hi_paper",
        class2: "",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "boomerang": {
        id: "boomerang",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "boulder": {
        id: "boulder",
        symbol: "?",
        class1: "hi_mineral",
        class2: "",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "bow": {
        id: "bow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "brass lantern": {
        id: "brass lantern",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "breastplate of righteousness": {
        id: "breastplate of righteousness",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "broadsword": {
        id: "broadsword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "bronze plate mail": {
        id: "bronze plate mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "bugle": {
        id: "bugle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "bullwhip": {
        id: "bullwhip",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "c-ration": {
        id: "c-ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "can of grease": {
        id: "can of grease",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "candelabrum of invocation": {
        id: "candelabrum of invocation",
        symbol: "?",
        class1: "hi_gold",
        class2: "",
        is_artifact: false,
        color: "HI_GOLD",
    },
    "candy bar": {
        id: "candy bar",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BRIGHT_BLUE",
    },
    "cap of salvation": {
        id: "cap of salvation",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "carrot": {
        id: "carrot",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "chain mail": {
        id: "chain mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "cheap plastic imitation of the amulet of yendor": {
        id: "cheap plastic imitation of the amulet of yendor",
        symbol: "?",
        class1: "hi_metal",
        class2: "",
        is_artifact: false,
        color: "HI_METAL",
    },
    "chest": {
        id: "chest",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "chrysoberyl": {
        id: "chrysoberyl",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "citrine": {
        id: "citrine",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "cleaver": {
        id: "cleaver",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "cloak of displacement": {
        id: "cloak of displacement",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "cloak of invisibility": {
        id: "cloak of invisibility",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BRIGHT_MAGENTA",
    },
    "cloak of magic resistance": {
        id: "cloak of magic resistance",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "cloak of protection": {
        id: "cloak of protection",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "clove of garlic": {
        id: "clove of garlic",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "club": {
        id: "club",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "cornuthaum": {
        id: "cornuthaum",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "corpse": {
        id: "corpse",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "cram ration": {
        id: "cram ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "cream pie": {
        id: "cream pie",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "credit card": {
        id: "credit card",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "crossbow": {
        id: "crossbow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "crossbow bolt": {
        id: "crossbow bolt",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "crysknife": {
        id: "crysknife",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "crystal ball": {
        id: "crystal ball",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_GLASS",
    },
    "crystal plate mail": {
        id: "crystal plate mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "dagger": {
        id: "dagger",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "dart": {
        id: "dart",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "demonbane": {
        id: "demonbane",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "dented pot": {
        id: "dented pot",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "diamond": {
        id: "diamond",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "dilithium crystal": {
        id: "dilithium crystal",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "divine covering": {
        id: "divine covering",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "doubled-edged blade": {
        id: "doubled-edged blade",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "dragonbane": {
        id: "dragonbane",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "drum of earthquake": {
        id: "drum of earthquake",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "dunce cap": {
        id: "dunce cap",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "dwarvish cloak": {
        id: "dwarvish cloak",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "dwarvish iron helm": {
        id: "dwarvish iron helm",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "dwarvish mattock": {
        id: "dwarvish mattock",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "dwarvish mithril-coat": {
        id: "dwarvish mithril-coat",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "dwarvish roundshield": {
        id: "dwarvish roundshield",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "dwarvish short sword": {
        id: "dwarvish short sword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "dwarvish spear": {
        id: "dwarvish spear",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "egg": {
        id: "egg",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "elixer of acid": {
        id: "acid",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "elixer of blindness": {
        id: "blindness",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "elixer of booze": {
        id: "booze",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "elixer of confusion": {
        id: "confusion",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "elixer of fruit juice": {
        id: "fruit juice",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "elixer of hallucination": {
        id: "hallucination",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "elixer of levitation": {
        id: "levitation",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "elixer of oil": {
        id: "oil",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "elixer of paralysis": {
        id: "paralysis",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_BRIGHT_GREEN",
    },
    "elixer of polymorph": {
        id: "polymorph",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "elixer of sickness": {
        id: "sickness",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "elixer of sleeping": {
        id: "sleeping",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "elixer of water": {
        id: "water",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "elven arrow": {
        id: "elven arrow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "elven boots": {
        id: "elven boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "elven bow": {
        id: "elven bow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "elven broadsword": {
        id: "elven broadsword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "elven cloak": {
        id: "elven cloak",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "elven dagger": {
        id: "elven dagger",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "elven leather helm": {
        id: "elven leather helm",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "elven mithril-coat": {
        id: "elven mithril-coat",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "elven shield": {
        id: "elven shield",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "elven short sword": {
        id: "elven short sword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "elven spear": {
        id: "elven spear",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "emerald": {
        id: "emerald",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "enormous meatball": {
        id: "enormous meatball",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "eucalyptus leaf": {
        id: "eucalyptus leaf",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "excalibur": {
        id: "excalibur",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "expensive camera": {
        id: "expensive camera",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "fauchard": {
        id: "fauchard",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "fedora": {
        id: "fedora",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "figurine": {
        id: "figurine",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "fire brand": {
        id: "fire brand",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "fire horn": {
        id: "fire horn",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "flail": {
        id: "flail",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "flint": {
        id: "flint",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "fluorite": {
        id: "fluorite",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "food ration": {
        id: "food ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "fortune cookie": {
        id: "fortune cookie",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "frost brand": {
        id: "frost brand",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "frost horn": {
        id: "frost horn",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "fumble boots": {
        id: "fumble boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "garnet": {
        id: "garnet",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_RED",
    },
    "gauntlets of dexterity": {
        id: "gauntlets of dexterity",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "gauntlets of fumbling": {
        id: "gauntlets of fumbling",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "gauntlets of power": {
        id: "gauntlets of power",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "giantslayer": {
        id: "giantslayer",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "glaive": {
        id: "glaive",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "gleaming armor": {
        id: "gleaming armor",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "glob of black pudding": {
        id: "glob of black pudding",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "glob of brown pudding": {
        id: "glob of brown pudding",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "glob of gray ooze": {
        id: "glob of gray ooze",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "glob of green slime": {
        id: "glob of green slime",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "gold dragon scale mail": {
        id: "gold dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_GOLD",
    },
    "gold dragon scales": {
        id: "gold dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_GOLD",
    },
    "gold piece": {
        id: "gold piece",
        symbol: "$",
        class1: "coins",
        class2: "pile of coins",
        is_artifact: false,
        color: "HI_GOLD",
    },
    "golden censer of incense": {
        id: "golden censer of incense",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "CLR_WHITE",
    },
    "gosple of the peace": {
        id: "gosple of the peace",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "gray dragon scale mail": {
        id: "gray dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "gray dragon scales": {
        id: "gray dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "grayswandir": {
        id: "grayswandir",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "green dragon scale mail": {
        id: "green dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "green dragon scales": {
        id: "green dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "grimtooth": {
        id: "grimtooth",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "CLR_RED",
    },
    "guisarme": {
        id: "guisarme",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "halberd": {
        id: "halberd",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "handkerchief of the apostle paul": {
        id: "handkerchief of the apostle paul",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "CLR_WHITE",
    },
    "hawaiian shirt": {
        id: "hawaiian shirt",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "heavy iron ball": {
        id: "heavy iron ball",
        symbol: "?",
        class1: "hi_metal",
        class2: "",
        is_artifact: false,
        color: "HI_METAL",
    },
    "helm of brilliance": {
        id: "helm of brilliance",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "helm of caution": {
        id: "helm of caution",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "helm of opposite alignment": {
        id: "helm of opposite alignment",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "helm of telepathy": {
        id: "helm of telepathy",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "helmet": {
        id: "helmet",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "high boots": {
        id: "high boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "horn of plenty": {
        id: "horn of plenty",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "humble sash": {
        id: "humble sash",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "ice box": {
        id: "ice box",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "iron chain": {
        id: "iron chain",
        symbol: "?",
        class1: "hi_metal",
        class2: "",
        is_artifact: false,
        color: "HI_METAL",
    },
    "iron shoes": {
        id: "iron shoes",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "jacinth": {
        id: "jacinth",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "jade": {
        id: "jade",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "jasper": {
        id: "jasper",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_RED",
    },
    "javelin": {
        id: "javelin",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "jet": {
        id: "jet",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "jumping boots": {
        id: "jumping boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "k-ration": {
        id: "k-ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "katana": {
        id: "katana",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "kelp frond": {
        id: "kelp frond",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "kicking boots": {
        id: "kicking boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "knife": {
        id: "knife",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "lance": {
        id: "lance",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "land mine": {
        id: "land mine",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_RED",
    },
    "large box": {
        id: "large box",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "large shield": {
        id: "large shield",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "leash": {
        id: "leash",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "leather armor": {
        id: "leather armor",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "leather cloak": {
        id: "leather cloak",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "leather drum": {
        id: "leather drum",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "leather gloves": {
        id: "leather gloves",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "leather jacket": {
        id: "leather jacket",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "lembas wafer": {
        id: "lembas wafer",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "lenses": {
        id: "lenses",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_GLASS",
    },
    "levitation boots": {
        id: "levitation boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "loadstone": {
        id: "loadstone",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "lock pick": {
        id: "lock pick",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "long sword": {
        id: "long sword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "low boots": {
        id: "low boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "lucern hammer": {
        id: "lucern hammer",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "luckstone": {
        id: "luckstone",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "lump of royal jelly": {
        id: "lump of royal jelly",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "mace": {
        id: "mace",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "magic flute": {
        id: "magic flute",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "magic harp": {
        id: "magic harp",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "magic lamp": {
        id: "magic lamp",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "magic whistle": {
        id: "magic whistle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "magicbane": {
        id: "magicbane",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "meat ring": {
        id: "meat ring",
        symbol: "?",
        class1: "clr_brown",
        class2: "",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "meat stick": {
        id: "meat stick",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "meatball": {
        id: "meatball",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "melon": {
        id: "melon",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BRIGHT_GREEN",
    },
    "mirror": {
        id: "mirror",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "mjollnir": {
        id: "mjollnir",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "morning star": {
        id: "morning star",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "mummy wrapping": {
        id: "mummy wrapping",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "novel": {
        id: "novel",
        symbol: "?",
        class1: "clr_bright_blue",
        class2: "",
        is_artifact: false,
        color: "CLR_BRIGHT_BLUE",
    },
    "obsidian": {
        id: "obsidian",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "ogresmasher": {
        id: "ogresmasher",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "oil lamp": {
        id: "oil lamp",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "oilskin cloak": {
        id: "oilskin cloak",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "oilskin sack": {
        id: "oilskin sack",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "opal": {
        id: "opal",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "orange": {
        id: "orange",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "orange dragon scale mail": {
        id: "orange dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "orange dragon scales": {
        id: "orange dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "orcish arrow": {
        id: "orcish arrow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcish bow": {
        id: "orcish bow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcish chain mail": {
        id: "orcish chain mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcish cloak": {
        id: "orcish cloak",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcish dagger": {
        id: "orcish dagger",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcish helm": {
        id: "orcish helm",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcish ring mail": {
        id: "orcish ring mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcish shield": {
        id: "orcish shield",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_RED",
    },
    "orcish short sword": {
        id: "orcish short sword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcish spear": {
        id: "orcish spear",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcrist": {
        id: "orcrist",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "CLR_BRIGHT_BLUE",
    },
    "pancake": {
        id: "pancake",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "partisan": {
        id: "partisan",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "pear": {
        id: "pear",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BRIGHT_GREEN",
    },
    "plate mail": {
        id: "plate mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "prophetic book of abundant healing": {
        id: "abundant healing",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "prophetic book of angelic help": {
        id: "angelic help",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "prophetic book of ascension": {
        id: "ascension",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "prophetic book of banishment": {
        id: "banishment",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_GOLD",
    },
    "prophetic book of bewilder": {
        id: "bewilder",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "prophetic book of blank paper": {
        id: "blank paper",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of cancellation": {
        id: "cancellation",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "prophetic book of cure blindness": {
        id: "cure blindness",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "prophetic book of cure sickness": {
        id: "cure sickness",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "prophetic book of discernment": {
        id: "discernment",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "prophetic book of divine ability": {
        id: "divine ability",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "prophetic book of divine concealment": {
        id: "divine concealment",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "prophetic book of door shall be open": {
        id: "door shall be open",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BRIGHT_MAGENTA",
    },
    "prophetic book of far sight": {
        id: "far sight",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "prophetic book of fiery tempest": {
        id: "fiery tempest",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of finger of judgement": {
        id: "finger of judgement",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of flame sphere": {
        id: "flame sphere",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "prophetic book of flesh renewed": {
        id: "flesh renewed",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of freeze sphere": {
        id: "freeze sphere",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "prophetic book of healing": {
        id: "healing",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "prophetic book of heavenly host": {
        id: "heavenly host",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BRIGHT_CYAN",
    },
    "prophetic book of hidden arrows": {
        id: "hidden arrows",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "prophetic book of leaping like a deer": {
        id: "leaping like a deer",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of light": {
        id: "light",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "prophetic book of lightning flash": {
        id: "lightning flash",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "prophetic book of move mountains": {
        id: "move mountains",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "prophetic book of noisome pestilence": {
        id: "noisome pestilence",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "prophetic book of northern wind": {
        id: "northern wind",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of pacification": {
        id: "pacification",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "prophetic book of path revealed": {
        id: "path revealed",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of piercing sight": {
        id: "piercing sight",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "prophetic book of protection": {
        id: "protection",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of quickening": {
        id: "quickening",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "prophetic book of rebuke": {
        id: "rebuke",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_RED",
    },
    "prophetic book of remove curse": {
        id: "remove curse",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of render unto caesar": {
        id: "render unto caesar",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "prophetic book of resist evil": {
        id: "resist evil",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "prophetic book of reveal foes": {
        id: "reveal foes",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "prophetic book of reveal sustenance": {
        id: "reveal sustenance",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "prophetic book of righteous fear": {
        id: "righteous fear",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BRIGHT_BLUE",
    },
    "prophetic book of seal entrance": {
        id: "seal entrance",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "prophetic book of staggering wine": {
        id: "staggering wine",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "CLR_BRIGHT_GREEN",
    },
    "prophetic book of tranquility": {
        id: "tranquility",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "prophetic book of transformation": {
        id: "transformation",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "quarterstaff": {
        id: "quarterstaff",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "ranseur": {
        id: "ranseur",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "red dragon scale mail": {
        id: "red dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_RED",
    },
    "red dragon scales": {
        id: "red dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_RED",
    },
    "riding blanket of the heavenly host": {
        id: "riding blanket of the heavenly host",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "CLR_WHITE",
    },
    "ring mail": {
        id: "ring mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "ring of adornment": {
        id: "adornment",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "ring of aggravate monster": {
        id: "aggravate monster",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "ring of cold resistance": {
        id: "cold resistance",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "ring of conflict": {
        id: "conflict",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_RED",
    },
    "ring of fire resistance": {
        id: "fire resistance",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_METAL",
    },
    "ring of free action": {
        id: "free action",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_METAL",
    },
    "ring of gain constitution": {
        id: "gain constitution",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "ring of gain strength": {
        id: "gain strength",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "ring of hunger": {
        id: "hunger",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "ring of increase accuracy": {
        id: "increase accuracy",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_RED",
    },
    "ring of increase damage": {
        id: "increase damage",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "ring of invisibility": {
        id: "invisibility",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_METAL",
    },
    "ring of levitation": {
        id: "levitation",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_RED",
    },
    "ring of poison resistance": {
        id: "poison resistance",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "ring of polymorph": {
        id: "polymorph",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "ring of polymorph control": {
        id: "polymorph control",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_BRIGHT_GREEN",
    },
    "ring of protection": {
        id: "protection",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "ring of protection from shape changers": {
        id: "protection from shape changers",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_BRIGHT_CYAN",
    },
    "ring of regeneration": {
        id: "regeneration",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "ring of searching": {
        id: "searching",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "ring of see invisible": {
        id: "see invisible",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_METAL",
    },
    "ring of shock resistance": {
        id: "shock resistance",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "ring of slow digestion": {
        id: "slow digestion",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_METAL",
    },
    "ring of stealth": {
        id: "stealth",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "ring of sustain ability": {
        id: "sustain ability",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "ring of teleport control": {
        id: "teleport control",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_GOLD",
    },
    "ring of teleportation": {
        id: "teleportation",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "ring of warning": {
        id: "warning",
        symbol: "=",
        class1: "rings",
        class2: "ring",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "robe": {
        id: "robe",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_RED",
    },
    "rock": {
        id: "rock",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "rod of ask and ye shall receive": {
        id: "ask and ye shall receive",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "rod of cancellation": {
        id: "cancellation",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "rod of consuming fire": {
        id: "consuming fire",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of divine concealment": {
        id: "divine concealment",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "rod of door shall be open": {
        id: "door shall be open",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of dove wings": {
        id: "dove wings",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "CLR_BRIGHT_CYAN",
    },
    "rod of final judgement": {
        id: "final judgement",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of heavenly host": {
        id: "heavenly host",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "rod of hidden arrows": {
        id: "hidden arrows",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of light": {
        id: "light",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_GLASS",
    },
    "rod of lightning flash": {
        id: "lightning flash",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of move mountains": {
        id: "move mountains",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of northern wind": {
        id: "northern wind",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of nothing": {
        id: "nothing",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "rod of quickening": {
        id: "quickening",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "rod of rebuke": {
        id: "rebuke",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "rod of resist evil": {
        id: "resist evil",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "rod of reveal secret things": {
        id: "reveal secret things",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "rod of revelation": {
        id: "revelation",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of seal entrance": {
        id: "seal entrance",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of staggering wine": {
        id: "staggering wine",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of tranquility": {
        id: "tranquility",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "rod of transformation": {
        id: "transformation",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "rod of understanding": {
        id: "understanding",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_GLASS",
    },
    "rubber hose": {
        id: "rubber hose",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "ruby": {
        id: "ruby",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_RED",
    },
    "runesword": {
        id: "runesword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "sack": {
        id: "sack",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "saddle": {
        id: "saddle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "sapphire": {
        id: "sapphire",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "scale mail": {
        id: "scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "scalpel": {
        id: "scalpel",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "scarlet cord of rahab": {
        id: "scarlet cord of rahab",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_MAGENTA",
    },
    "scimitar": {
        id: "scimitar",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "shield of faith": {
        id: "shield of faith",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "shield of reflection": {
        id: "shield of reflection",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "shimmering dragon scale mail": {
        id: "shimmering dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "shimmering dragon scales": {
        id: "shimmering dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "short sword": {
        id: "short sword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "shuriken": {
        id: "shuriken",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "silver arrow": {
        id: "silver arrow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "silver dagger": {
        id: "silver dagger",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "silver mace": {
        id: "silver mace",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "silver saber": {
        id: "silver saber",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "silver spear": {
        id: "silver spear",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "skeleton key": {
        id: "skeleton key",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "slime mold": {
        id: "slime mold",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "sling": {
        id: "sling",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "small shield": {
        id: "small shield",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "snickersnee": {
        id: "snickersnee",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "spear": {
        id: "spear",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "speed boots": {
        id: "speed boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "spetum": {
        id: "spetum",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "splash of acid venom": {
        id: "splash of acid venom",
        symbol: "?",
        class1: "hi_organic",
        class2: "",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "splash of blinding venom": {
        id: "splash of blinding venom",
        symbol: "?",
        class1: "hi_organic",
        class2: "",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "splint mail": {
        id: "splint mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "sprig of wolfsbane": {
        id: "sprig of wolfsbane",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "staff of signs and wonders": {
        id: "staff of signs and wonders",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "CLR_MAGENTA",
    },
    "statue": {
        id: "statue",
        symbol: "?",
        class1: "clr_white",
        class2: "",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "stethoscope": {
        id: "stethoscope",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "stiletto": {
        id: "stiletto",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "sting": {
        id: "sting",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "CLR_BRIGHT_BLUE",
    },
    "stormbringer": {
        id: "stormbringer",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "strange object": {
        id: "strange object",
        symbol: "?",
        class1: "hi_metal",
        class2: "",
        is_artifact: false,
        color: "HI_METAL",
    },
    "studded leather armor": {
        id: "studded leather armor",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "sunsword": {
        id: "sunsword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "sword of the spirit": {
        id: "sword of the spirit",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "t-shirt": {
        id: "t-shirt",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "tallow candle": {
        id: "tallow candle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "the eye of the aethiopica": {
        id: "the eye of the aethiopica",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the eyes of the overworld": {
        id: "the eyes of the overworld",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the heart of ahriman": {
        id: "the heart of ahriman",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the longbow of diana": {
        id: "the longbow of diana",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the magic mirror of merlin": {
        id: "the magic mirror of merlin",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the master key of thievery": {
        id: "the master key of thievery",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the mitre of holiness": {
        id: "the mitre of holiness",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the orb of detection": {
        id: "the orb of detection",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the orb of fate": {
        id: "the orb of fate",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the palantir of westernesse": {
        id: "the palantir of westernesse",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the platinum yendorian express card": {
        id: "the platinum yendorian express card",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the sceptre of might": {
        id: "the sceptre of might",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the staff of aesculapius": {
        id: "the staff of aesculapius",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the tsurugi of muramasa": {
        id: "the tsurugi of muramasa",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "thurible": {
        id: "thurible",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "tin": {
        id: "tin",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tin opener": {
        id: "tin opener",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tin whistle": {
        id: "tin whistle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tinning kit": {
        id: "tinning kit",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tooled horn": {
        id: "tooled horn",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "topaz": {
        id: "topaz",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "torn piece of cloth": {
        id: "torn piece of cloth",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "touchstone": {
        id: "touchstone",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "towel": {
        id: "towel",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "trident": {
        id: "trident",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tripe ration": {
        id: "tripe ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "trollsbane": {
        id: "trollsbane",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "trusty sandals": {
        id: "trusty sandals",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "tsurugi": {
        id: "tsurugi",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "turquoise": {
        id: "turquoise",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "two-handed sword": {
        id: "two-handed sword",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "uruk-hai shield": {
        id: "uruk-hai shield",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_METAL",
    },
    "verse of blank paper": {
        id: "blank paper",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of confound foes": {
        id: "confound foes",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of consuming fire": {
        id: "consuming fire",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of correction": {
        id: "correction",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of discernment": {
        id: "discernment",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of dove wings": {
        id: "dove wings",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of fire and brimstone": {
        id: "fire and brimstone",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of former things forgotten": {
        id: "former things forgotten",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of heavenly host": {
        id: "heavenly host",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of iron sharpens iron": {
        id: "iron sharpens iron",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of judgement to the wicked": {
        id: "judgement to the wicked",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of light": {
        id: "light",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of mail": {
        id: "mail",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of no covering": {
        id: "no covering",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of path revealed": {
        id: "path revealed",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of remove curse": {
        id: "remove curse",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of render unto caesar": {
        id: "render unto caesar",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of renewal": {
        id: "renewal",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of reveal mana": {
        id: "reveal mana",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of righteous fear": {
        id: "righteous fear",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of shaken earth": {
        id: "shaken earth",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of spiritual armor": {
        id: "spiritual armor",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "verse of subdue beast": {
        id: "subdue beast",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "vorpal blade": {
        id: "vorpal blade",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "voulge": {
        id: "voulge",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "war hammer": {
        id: "war hammer",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "water walking boots": {
        id: "water walking boots",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "wax candle": {
        id: "wax candle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "werebane": {
        id: "werebane",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "white dragon scale mail": {
        id: "white dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "white dragon scales": {
        id: "white dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "wooden flute": {
        id: "wooden flute",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "wooden harp": {
        id: "wooden harp",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "worm tooth": {
        id: "worm tooth",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "writing tablet": {
        id: "writing tablet",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_RED",
    },
    "ya": {
        id: "ya",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_METAL",
    },
    "yellow dragon scale mail": {
        id: "yellow dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "yellow dragon scales": {
        id: "yellow dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "yumi": {
        id: "yumi",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
};
