-- Map generated by RighteousHack Map Editor
-- 2026-02-14
-- Feel free to edit by hand
des.level_init({ style = "solidfill", fg = ".", bg = "-" });
des.level_flags("noteleport", "hardfloor", "noflip", "nomongen")

des.map([[
|---------------------------------------------------------------------------
|...............................|..........................................|
|...............................|..........................................|
|...............................|..........................................|
|...............................|...}}}}}}}................................|
|...............................|...}LLLLL}................................|
|...............................|...}LLLLL}..T.............................|
|...............................|...}LLLLL}..T.............................|
|...............................|...}LLLLL}................................|
|...............................|...}LLLLL}..T.............................|
|...............................|...}LLLLL}..T.............................|
|...................................}LLLLL}................................|
|...............................|...}LLLLL}................................|
|...............................|...}}}}}}}................................|
|...............................|..........................................|
|...............................|..........................................|
|...............................|..........................................|
|...............................|..........................................|
|...............................|..........................................|
|---------------------------------------------------------------------------
]]);

-- Lighting regions
des.region(selection.area(20,02,30,12), "lit")
des.region(selection.area(49,02,59,11), "lit")
des.region(selection.area(35,02,43,15), "lit")

des.monster({ id = "angel", x = 21, y = 03, peaceful = 1 });
des.monster({ id = "angel", x = 24, y = 03, peaceful = 1 });
des.monster({ id = "angel", x = 21, y = 07, peaceful = 1 });
des.monster({ id = "angel", x = 24, y = 07, peaceful = 1 });


des.object({ id = "gleaming armor", x = 54, y = 07, buc = "blessed", name = "breastplate of righteousness" });
-- des.object({ id = "cap of salvation", x = 55, y = 07, buc = "blessed" });
-- des.object({ id = "sword of the spirit", x = 54, y = 08, buc = "blessed" });
-- des.object({ id = "gosple of the peace", x = 55, y = 08, buc = "blessed" });
-- des.object({ id = "shield of faith", x = 56, y = 08, buc = "blessed" });

des.door({ x = 32, y = 11, state = "secret" });
des.room({ x = 67, y = 01, w = 08, h = 09, type = "shop", lit = 1, filled=1,
             contents = function()
                des.door({ state="closed", wall="west" })
             end  });
des.room({ x = 67, y = 12, w = 08, h = 07, type = "potion shop", lit = 1, filled=1,
             contents = function()
                des.door({ state="closed", wall="west" })
             end 
            });

des.gold({ x = 49, y = 11, amount = "100" });
des.gold({ x = 50, y = 11, amount = "100" });
des.gold({ x = 51, y = 11, amount = "100" });
des.gold({ x = 52, y = 11, amount = "100" });
des.gold({ x = 53, y = 11, amount = "100" });
des.gold({ x = 54, y = 11, amount = "100" });
des.gold({ x = 55, y = 11, amount = "100" });
des.gold({ x = 56, y = 11, amount = "100" });
des.gold({ x = 57, y = 11, amount = "100" });
des.gold({ x = 58, y = 11, amount = "100" });
des.gold({ x = 59, y = 11, amount = "100" });
des.gold({ x = 49, y = 02, amount = "100" });
des.gold({ x = 50, y = 02, amount = "100" });
des.gold({ x = 51, y = 02, amount = "100" });
des.gold({ x = 52, y = 02, amount = "100" });
des.gold({ x = 53, y = 02, amount = "100" });
des.gold({ x = 54, y = 02, amount = "100" });
des.gold({ x = 55, y = 02, amount = "100" });
des.gold({ x = 56, y = 02, amount = "100" });
des.gold({ x = 57, y = 02, amount = "100" });
des.gold({ x = 58, y = 02, amount = "100" });
des.gold({ x = 59, y = 02, amount = "100" });
des.gold({ x = 52, y = 04, amount = "100" });
des.gold({ x = 53, y = 04, amount = "100" });
des.gold({ x = 54, y = 04, amount = "100" });
des.gold({ x = 55, y = 04, amount = "100" });
des.gold({ x = 56, y = 04, amount = "100" });
des.gold({ x = 57, y = 04, amount = "100" });
des.feature({ x = 54, y = 14, type = "throne" });
des.trap({ x = 49, y = 12, type = "teleport" });
des.trap({ x = 59, y = 12, type = "teleport" });
des.trap({ x = 59, y = 01, type = "teleport" });
des.trap({ x = 49, y = 01, type = "teleport" });
des.engraving({ x = 59, y = 06, type = "burn", text = "An interesting message..." });
des.engraving({ x = 49, y = 06, type = "burn", text = "An interesting message..." });
des.altar({ x = 49, y = 04, align = "law", type = "altar" });
des.grave({ x = 51, y = 07, text = "Here lies someone..." });
des.feature({ x = 54, y = 17, type = "sink" });