-- Map generated by RighteousHack Map Editor
-- 2026-02-14
-- Feel free to edit by hand

des.level_init({ style = "solidfill", fg = ".", bg = "-" });
des.level_flags("noteleport", "noflip", "hardfloor", "nomongen")


des.map([[
|---------------------------------------------------------------------------
|...............................|.................................|........|
|...............................|.................................|........|
|...............................|.................................|........|
|...............................|...}}}}}}}.......................|........|
|...............................|...}LLLLL}.......................|........|
|...............................|...}LLLLL}..T....................+........|
|...............................|...}LLLLL}..T....................|........|
|...............................|...}LLLLL}.......................|........|
|...............................|...}LLLLL}..T....................|........|
|...............................|...}LLLLL}..T....................|--------|
|...................................}LLLLL}.......................|--------|
|...............................|...}LLLLL}.......................|........|
|...............................|...}}}}}}}..........{{{..........|........|
|...............................|.................................|........|
|...............................|.................................|........|
|...............................|.................................+........|
|...............................|.................................|........|
|.................................................................|........|
|---------------------------------------------------------------------------
]]);

-- Lighting regions
des.region(selection.area(20,02,30,12), "lit")
des.region(selection.area(49,02,59,11), "lit")
des.region(selection.area(35,02,43,15), "lit")

des.monster({ id = "angel", x = 21, y = 03, peaceful = 1 });
des.monster({ id = "angel", x = 24, y = 03, peaceful = 1 });
des.monster({ id = "angel", x = 21, y = 07, peaceful = 1 });
des.monster({ id = "angel", x = 24, y = 07, peaceful = 1 });


des.object({ id = "gleaming armor", x = 53, y = 04, name = "breastplate of righteousness" });
des.object({ id = "ancient defense", x = 54, y = 04, name = "shield of faith" });
des.object({ id = "trusty sandals", x = 55, y = 04, name = "gosple of the peace" });
des.object({ id = "divine covering", x = 53, y = 05, name = "cap of salvation" });
des.object({ id = "doubled-edged blade", x = 54, y = 05, name = "sword of the spirit" });
des.object({ id = "humble sash", x = 55, y = 05, name = "belt of truth" });
des.object({ x = 41, y = 13, class = "?" });


--des.room({ type = "shop", x = 67, y = 01, w = 08, h = 09,  lit = 1, filled = 1 });
--des.room({ type = "potion shop", x = 67, y = 12, w = 08, h = 07,  lit = 1, filled = 1 });


des.region({ x = 67, y = 01, w = 08, h = 09,lit=1,type="shop",filled=1 })
des.region({ region={67,12,75,19},lit=1,type="potion shop",filled=1 })

des.trap();
des.trap();
des.trap();
des.trap();
des.altar({ x = 49, y = 04 });
des.feature({ x = 54, y = 07, type = "throne" });
des.feature({ x = 54, y = 09, type = "sink" });