const allObjects = {
    "agate": {
        id: "agate",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "amber": {
        id: "amber",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "amethyst": {
        id: "amethyst",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "amnesia": {
        id: "amnesia",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "amulet of change": {
        id: "amulet of change",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of esp": {
        id: "amulet of esp",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of flying": {
        id: "amulet of flying",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of guarding": {
        id: "amulet of guarding",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of life saving": {
        id: "amulet of life saving",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of magical breathing": {
        id: "amulet of magical breathing",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of reflection": {
        id: "amulet of reflection",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of restful sleep": {
        id: "amulet of restful sleep",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of strangulation": {
        id: "amulet of strangulation",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet of unchanging": {
        id: "amulet of unchanging",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "amulet versus poison": {
        id: "amulet versus poison",
        symbol: "\"",
        class1: "amulets",
        class2: "amulet",
        is_artifact: false,
        color: "None",
    },
    "apostolic writing kit": {
        id: "apostolic writing kit",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_WHITE",
    },
    "apple": {
        id: "apple",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_RED",
    },
    "aquamarine": {
        id: "aquamarine",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "ask and ye shall receive": {
        id: "ask and ye shall receive",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "bag of holding": {
        id: "bag of holding",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "bag of tricks": {
        id: "bag of tricks",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "banana": {
        id: "banana",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "beartrap": {
        id: "beartrap",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "bell": {
        id: "bell",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "belt of truth": {
        id: "belt of truth",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "black dragon scale mail": {
        id: "black dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "black dragon scales": {
        id: "black dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "black opal": {
        id: "black opal",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "blank paper": {
        id: "blank paper",
        symbol: "+",
        class1: "prophetic books",
        class2: "prophetic book",
        is_artifact: false,
        color: "HI_PAPER",
    },
    "blindfold": {
        id: "blindfold",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "blue dragon scale mail": {
        id: "blue dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "blue dragon scales": {
        id: "blue dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "bow": {
        id: "bow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "brass lantern": {
        id: "brass lantern",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "breastplate of righteousness": {
        id: "breastplate of righteousness",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "bugle": {
        id: "bugle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "c-ration": {
        id: "c-ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "can of grease": {
        id: "can of grease",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "cancellation": {
        id: "cancellation",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "candy bar": {
        id: "candy bar",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BRIGHT_BLUE",
    },
    "cap of salvation": {
        id: "cap of salvation",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "carrot": {
        id: "carrot",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "charging": {
        id: "charging",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "chest": {
        id: "chest",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "chrysoberyl": {
        id: "chrysoberyl",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "citrine": {
        id: "citrine",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "cleaver": {
        id: "cleaver",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "clove of garlic": {
        id: "clove of garlic",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "cold": {
        id: "cold",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "confound foes": {
        id: "confound foes",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "confuse monster": {
        id: "confuse monster",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "consuming fire": {
        id: "consuming fire",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "corpse": {
        id: "corpse",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "correction": {
        id: "correction",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "cram ration": {
        id: "cram ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "cream pie": {
        id: "cream pie",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "create monster": {
        id: "create monster",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "credit card": {
        id: "credit card",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "crossbow": {
        id: "crossbow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "crystal ball": {
        id: "crystal ball",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_GLASS",
    },
    "death": {
        id: "death",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "demonbane": {
        id: "demonbane",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "destroy armor": {
        id: "destroy armor",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "diamond": {
        id: "diamond",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "digging": {
        id: "digging",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "dilithium crystal": {
        id: "dilithium crystal",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "discernment": {
        id: "discernment",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "divine concealment": {
        id: "divine concealment",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "door shall be open": {
        id: "door shall be open",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "dove wings": {
        id: "dove wings",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "dragonbane": {
        id: "dragonbane",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "drum of earthquake": {
        id: "drum of earthquake",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "earth": {
        id: "earth",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "egg": {
        id: "egg",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "elven bow": {
        id: "elven bow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "emerald": {
        id: "emerald",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "enchant armor": {
        id: "enchant armor",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "enchant weapon": {
        id: "enchant weapon",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "enlightenment": {
        id: "enlightenment",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "enormous meatball": {
        id: "enormous meatball",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "eucalyptus leaf": {
        id: "eucalyptus leaf",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "excalibur": {
        id: "excalibur",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "expensive camera": {
        id: "expensive camera",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "extra healing": {
        id: "extra healing",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_RED",
    },
    "figurine": {
        id: "figurine",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "final judgement": {
        id: "final judgement",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "fire": {
        id: "fire",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "fire and brimstone": {
        id: "fire and brimstone",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "fire brand": {
        id: "fire brand",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "fire horn": {
        id: "fire horn",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "flint": {
        id: "flint",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "fluorite": {
        id: "fluorite",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "food detection": {
        id: "food detection",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "food ration": {
        id: "food ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "former things forgotten": {
        id: "former things forgotten",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "fortune cookie": {
        id: "fortune cookie",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "frost brand": {
        id: "frost brand",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "frost horn": {
        id: "frost horn",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "full healing": {
        id: "full healing",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "gain energy": {
        id: "gain energy",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "gain level": {
        id: "gain level",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "garnet": {
        id: "garnet",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_RED",
    },
    "genocide": {
        id: "genocide",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "giantslayer": {
        id: "giantslayer",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "glob of black pudding": {
        id: "glob of black pudding",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "glob of brown pudding": {
        id: "glob of brown pudding",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "glob of gray ooze": {
        id: "glob of gray ooze",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "glob of green slime": {
        id: "glob of green slime",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "gold detection": {
        id: "gold detection",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "gold dragon scale mail": {
        id: "gold dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_GOLD",
    },
    "gold dragon scales": {
        id: "gold dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "HI_GOLD",
    },
    "golden censer of incense": {
        id: "golden censer of incense",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_WHITE",
    },
    "gosple of the peace": {
        id: "gosple of the peace",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "gray dragon scale mail": {
        id: "gray dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "gray dragon scales": {
        id: "gray dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "grayswandir": {
        id: "grayswandir",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "green dragon scale mail": {
        id: "green dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "green dragon scales": {
        id: "green dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "grimtooth": {
        id: "grimtooth",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_RED",
    },
    "handkerchief of the apostle paul": {
        id: "handkerchief of the apostle paul",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_WHITE",
    },
    "healing": {
        id: "healing",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "heavenly host": {
        id: "heavenly host",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "hidden arrows": {
        id: "hidden arrows",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "horn of plenty": {
        id: "horn of plenty",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "ice box": {
        id: "ice box",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "identify": {
        id: "identify",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "invisibility": {
        id: "invisibility",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_BRIGHT_BLUE",
    },
    "iron sharpens iron": {
        id: "iron sharpens iron",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "jacinth": {
        id: "jacinth",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "jade": {
        id: "jade",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "jasper": {
        id: "jasper",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_RED",
    },
    "jet": {
        id: "jet",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "judgement to the wicked": {
        id: "judgement to the wicked",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "k-ration": {
        id: "k-ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "kelp frond": {
        id: "kelp frond",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "land mine": {
        id: "land mine",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_RED",
    },
    "large box": {
        id: "large box",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "leash": {
        id: "leash",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "leather drum": {
        id: "leather drum",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "lembas wafer": {
        id: "lembas wafer",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "lenses": {
        id: "lenses",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_GLASS",
    },
    "light": {
        id: "light",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "lightning": {
        id: "lightning",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "lightning flash": {
        id: "lightning flash",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "loadstone": {
        id: "loadstone",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "lock pick": {
        id: "lock pick",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "locking": {
        id: "locking",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "luckstone": {
        id: "luckstone",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "lump of royal jelly": {
        id: "lump of royal jelly",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "magic flute": {
        id: "magic flute",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "magic harp": {
        id: "magic harp",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "magic lamp": {
        id: "magic lamp",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "magic mapping": {
        id: "magic mapping",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "magic missile": {
        id: "magic missile",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "magic whistle": {
        id: "magic whistle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "magicbane": {
        id: "magicbane",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "mail": {
        id: "mail",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "make invisible": {
        id: "make invisible",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_MINERAL",
    },
    "meat stick": {
        id: "meat stick",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "meatball": {
        id: "meatball",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "melon": {
        id: "melon",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BRIGHT_GREEN",
    },
    "mirror": {
        id: "mirror",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "mjollnir": {
        id: "mjollnir",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "monster detection": {
        id: "monster detection",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "move mountains": {
        id: "move mountains",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "no covering": {
        id: "no covering",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "northern wind": {
        id: "northern wind",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "nothing": {
        id: "nothing",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "object detection": {
        id: "object detection",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "obsidian": {
        id: "obsidian",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "ogresmasher": {
        id: "ogresmasher",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "oil lamp": {
        id: "oil lamp",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "oilskin sack": {
        id: "oilskin sack",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "opal": {
        id: "opal",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "opening": {
        id: "opening",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "orange": {
        id: "orange",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "orange dragon scale mail": {
        id: "orange dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "orange dragon scales": {
        id: "orange dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_ORANGE",
    },
    "orcish bow": {
        id: "orcish bow",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "CLR_BLACK",
    },
    "orcrist": {
        id: "orcrist",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_BRIGHT_BLUE",
    },
    "pancake": {
        id: "pancake",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "path revealed": {
        id: "path revealed",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "pear": {
        id: "pear",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BRIGHT_GREEN",
    },
    "polymorph": {
        id: "polymorph",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "probing": {
        id: "probing",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "punishment": {
        id: "punishment",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "quickening": {
        id: "quickening",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "rebuke": {
        id: "rebuke",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "red dragon scale mail": {
        id: "red dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_RED",
    },
    "red dragon scales": {
        id: "red dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_RED",
    },
    "remove curse": {
        id: "remove curse",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "render unto caesar": {
        id: "render unto caesar",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "renewal": {
        id: "renewal",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "resist evil": {
        id: "resist evil",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "restore ability": {
        id: "restore ability",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_BRIGHT_MAGENTA",
    },
    "reveal mana": {
        id: "reveal mana",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "reveal secret things": {
        id: "reveal secret things",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "revelation": {
        id: "revelation",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "riding blanket of the heavenly host": {
        id: "riding blanket of the heavenly host",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_WHITE",
    },
    "righteous fear": {
        id: "righteous fear",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "rock": {
        id: "rock",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "ruby": {
        id: "ruby",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_RED",
    },
    "sack": {
        id: "sack",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "saddle": {
        id: "saddle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "sapphire": {
        id: "sapphire",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BLUE",
    },
    "scare monster": {
        id: "scare monster",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "scarlet cord of rahab": {
        id: "scarlet cord of rahab",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_MAGENTA",
    },
    "seal entrance": {
        id: "seal entrance",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "see invisible": {
        id: "see invisible",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "shaken earth": {
        id: "shaken earth",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "shield of faith": {
        id: "shield of faith",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "shimmering dragon scale mail": {
        id: "shimmering dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "shimmering dragon scales": {
        id: "shimmering dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_CYAN",
    },
    "skeleton key": {
        id: "skeleton key",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "sleep": {
        id: "sleep",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "slime mold": {
        id: "slime mold",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_ORGANIC",
    },
    "sling": {
        id: "sling",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_LEATHER",
    },
    "slow monster": {
        id: "slow monster",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "snickersnee": {
        id: "snickersnee",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "speed": {
        id: "speed",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "speed monster": {
        id: "speed monster",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "spiritual armor": {
        id: "spiritual armor",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "sprig of wolfsbane": {
        id: "sprig of wolfsbane",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "staff of signs and wonders": {
        id: "staff of signs and wonders",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_MAGENTA",
    },
    "staggering wine": {
        id: "staggering wine",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "stethoscope": {
        id: "stethoscope",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "sting": {
        id: "sting",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "CLR_BRIGHT_BLUE",
    },
    "stinking cloud": {
        id: "stinking cloud",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "stormbringer": {
        id: "stormbringer",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "striking": {
        id: "striking",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "subdue beast": {
        id: "subdue beast",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "sunsword": {
        id: "sunsword",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "sword of the spirit": {
        id: "sword of the spirit",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "tallow candle": {
        id: "tallow candle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "taming": {
        id: "taming",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "teleportation": {
        id: "teleportation",
        symbol: "?",
        class1: "scrolls",
        class2: "scroll",
        is_artifact: false,
        color: "None",
    },
    "the eye of the aethiopica": {
        id: "the eye of the aethiopica",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the eyes of the overworld": {
        id: "the eyes of the overworld",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the heart of ahriman": {
        id: "the heart of ahriman",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the longbow of diana": {
        id: "the longbow of diana",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the magic mirror of merlin": {
        id: "the magic mirror of merlin",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the master key of thievery": {
        id: "the master key of thievery",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the mitre of holiness": {
        id: "the mitre of holiness",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the orb of detection": {
        id: "the orb of detection",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the orb of fate": {
        id: "the orb of fate",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the palantir of westernesse": {
        id: "the palantir of westernesse",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the platinum yendorian express card": {
        id: "the platinum yendorian express card",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the sceptre of might": {
        id: "the sceptre of might",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the staff of aesculapius": {
        id: "the staff of aesculapius",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "the tsurugi of muramasa": {
        id: "the tsurugi of muramasa",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "thurible": {
        id: "thurible",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "tin": {
        id: "tin",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tin opener": {
        id: "tin opener",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tin whistle": {
        id: "tin whistle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tinning kit": {
        id: "tinning kit",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_METAL",
    },
    "tooled horn": {
        id: "tooled horn",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "topaz": {
        id: "topaz",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "torn piece of cloth": {
        id: "torn piece of cloth",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_CLOTH",
    },
    "touchstone": {
        id: "touchstone",
        symbol: "`",
        class1: "large stones",
        class2: "boulder or statue",
        is_artifact: false,
        color: "CLR_GRAY",
    },
    "towel": {
        id: "towel",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_MAGENTA",
    },
    "tranquility": {
        id: "tranquility",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_METAL",
    },
    "transformation": {
        id: "transformation",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_SILVER",
    },
    "tripe ration": {
        id: "tripe ration",
        symbol: "%",
        class1: "food",
        class2: "piece of food",
        is_artifact: false,
        color: "CLR_BROWN",
    },
    "trollsbane": {
        id: "trollsbane",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "turquoise": {
        id: "turquoise",
        symbol: "*",
        class1: "rocks",
        class2: "gem or rock",
        is_artifact: false,
        color: "CLR_GREEN",
    },
    "undead turning": {
        id: "undead turning",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_COPPER",
    },
    "understanding": {
        id: "understanding",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_GLASS",
    },
    "vorpal blade": {
        id: "vorpal blade",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "wax candle": {
        id: "wax candle",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "werebane": {
        id: "werebane",
        symbol: "?",
        class1: "unknown",
        class2: "",
        is_artifact: true,
        color: "NO_COLOR",
    },
    "white dragon scale mail": {
        id: "white dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "white dragon scales": {
        id: "white dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_WHITE",
    },
    "wiggy gain ability": {
        id: "wiggy gain ability",
        symbol: "!",
        class1: "elixers",
        class2: "elixer",
        is_artifact: false,
        color: "CLR_RED",
    },
    "wishing": {
        id: "wishing",
        symbol: "/",
        class1: "rods",
        class2: "rod",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "wooden flute": {
        id: "wooden flute",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "wooden harp": {
        id: "wooden harp",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "HI_WOOD",
    },
    "writing tablet": {
        id: "writing tablet",
        symbol: "(",
        class1: "tools",
        class2: "useful item (pick-axe, key, lamp...)",
        is_artifact: false,
        color: "CLR_RED",
    },
    "yellow dragon scale mail": {
        id: "yellow dragon scale mail",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "yellow dragon scales": {
        id: "yellow dragon scales",
        symbol: "[",
        class1: "armor",
        class2: "suit or piece of armor",
        is_artifact: false,
        color: "CLR_YELLOW",
    },
    "yumi": {
        id: "yumi",
        symbol: ")",
        class1: "weapons",
        class2: "weapon",
        is_artifact: false,
        color: "HI_WOOD",
    },
};
